name: Deploy stage version
on:
  pull_request:
    branches: [stg]
jobs:
    build:
      name: Previous cleaning
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: SSH for previous scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          script: |
            sudo rm -R /usr/app/stg*
            sudo mkdir /usr/app/stg
      - name: Deployment in home folder
        uses: srueda99/scp-action@stable
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          origin: "./*"
          destination: "/home/${{ secrets.SERVER_USER }}/"
      - name: Moving files to usr/app/stg
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          script: |
            sudo mv /home/${{ secrets.SERVER_USER }}/* /usr/app/stg/
            sudo mv /usr/app/dev/.env /usr/app/stg/
            sudo npm install --prefix /usr/app/stg