name: Deploy development version
on:
  push:
    branches: [dev]
# env:
#   PORT: ${{ secrets.PORT }}
#   AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
#   BKTMG_SECRET_KEY: ${{ secrets.BKTMG_SECRET_KEY }}
#   AWS_REGION: ${{ secrets.AWS_REGION }}
#   BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
jobs:
    build:
      name: Deploying DEV
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: SSH for previous scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          #envs: PORT,AWS_ACCESS_KEY,BKTMG_SECRET_KEY,AWS_REGION,BUCKET_NAME
          script: |
            sudo mkdir /usr/app-dev2
            sudo rm -R /usr/app-dev*
            sudo mkdir /usr/app-dev
            sudo apt update
            sudo apt upgrade -y
            sudo apt install awscli -y
            sudo apt install nodejs -y
            sudo apt install npm -y
            sudo apt update
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }} --profile bucketmg
            aws configure set aws_secret_access_key ${{ secrets.BKTMG_SECRET_KEY }} --profile bucketmg
            aws configure set region ${{ secrets.AWS_REGION }} --profile bucketmg
            aws configure set output json --profile bucketmg
      - name: Deployment in home folder
        uses: siva1024/scp-deployer@latest
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          source: "./*"
          target: "/home/${{ secrets.SERVER_USER }}/"
      - name: Moving files to usr/app-dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          script: |
            sudo mv /home/${{ secrets.SERVER_USER }}/* /usr/app-dev/