name: Deploy development version
on:
  push:
    branches: [dev]
env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  BKTMG_SECRET_KEY: ${{ secrets.BKTMG_SECRET_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
jobs:
    build:
      name: Deploying DEV
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: SSH for previous scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          envs: AWS_ACCESS_KEY,BKTMG_SECRET_KEY,AWS_REGION,BUCKET_NAME
          script: |
            export PORT=80
            sudo mkdir /usr/app-dev2
            sudo rm -R /usr/app-dev*
            sudo mkdir /usr/app-dev
            sudo apt-get update
            sudo apt-get upgrade -y
            sudo apt-get install awscli -y
            sudo apt-get install nodejs -y
            sudo apt-get install npm -y
            sudo apt-get update
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }} --profile bucketmg
            aws configure set aws_secret_access_key ${{ secrets.BKTMG_SECRET_KEY }} --profile bucketmg
            aws configure set region ${{ secrets.AWS_REGION }} --profile bucketmg
            aws configure set output json --profile bucketmg
      - name: Deployment in home folder
        uses: siva1024/scp-deployer@latest
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          source: "./*"
          target: "/home/${{ secrets.SERVER_USER }}/"
      - name: Moving files to usr/app-dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          script: |
            export PORT=80
            sudo mv /home/${{ secrets.SERVER_USER }}/* /usr/app-dev/
            sudo npm install --prefix /usr/app-dev
            sudo npm update /usr/app-dev