name: Deploy production version
on:
  pull_request:
    branches: [main]
jobs:
    build:
      name: Previous cleaning
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: SSH for previous scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          script: |
            sudo mkdir /usr/app/prod2
            sudo rm -R /usr/app/prod*
            sudo mkdir /usr/app/prod
      - name: Deployment in home folder
        uses: siva1024/scp-deployer@latest
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          source: "./*"
          target: "/home/${{ secrets.SERVER_USER }}/"
      - name: Moving files to usr/app/prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          script: |
            sudo mv /home/${{ secrets.SERVER_USER }}/* /usr/app/prod/
            sudo cp /usr/app/stg/.env /usr/app/prod/
            sudo npm install --prefix /usr/app/prod